version: '3'
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    links:
      - app1
      - app2
    environment:
      PORT: "3001-3002"
    depends_on:
      - app1
      - app2
  app1:
    image: nicopaez/password-api
    ports:
      - "3001:3000"
  app2:
    image: nicopaez/password-api
    ports:
      - "3002:3000"
